### ISSUE TITLE
Failure when trying to read UDP

### ISSUE THREAD

**Issue by razvanbrasoveanu** [adduc/phpmodbus#3]
Hi!

I get the following exception when trying to read the data:

readCoils: START
Connected
Packet: e4e30000000600013000000c
Send
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 

Exception: Watchdog time expired [ 5 sec]!!! Connection to 192.168.132.231 is not established. in C:\xampp\htdocs\Phpmodbus\ModbusMaster.php:160 Stack trace: #0 C:\xampp\htdocs\Phpmodbus\ModbusMaster.php(228): ModbusMaster->rec() #1 C:\xampp\htdocs\index.php(10): ModbusMaster->readCoils(0, 12288, 12) #2 {main}

Any idea why?

Thank you!

**Comment by carlos-granadeno** [comment]
Hi, I recently downloaded this library, and I had made a lot of attempts but it didn't connect.  I read in a Siemens forum, when you try to connect to a modbus tcp you have to use port 510, not the 502, because that is reserved for the master, and when you try to read the data, your pc is a client.

**Comment by hsathyabhama** [comment]
readCoils: START
Connected
Packet: a0cf0000000600010001000c
Send
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Exception: Watchdog time expired [ 5 sec]!!! Connection to 192.168.0.9 is not established. in F:\xampp\htdocs\phpmodbus\Phpmodbus\ModbusMaster.php:165 Stack trace: #0 F:\xampp\htdocs\phpmodbus\Phpmodbus\ModbusMaster.php(233): ModbusMaster->rec() #1 F:\xampp\htdocs\phpmodbus\examples\index.php(10): ModbusMaster->readCoils(0, 1, 12) #2 {main}..

same error for me also. Kindly help me to find a solution. Thanks in advance..
